package com.myspace.ceptest;



import fraud.analysis.demo.transaction.Transaction;


rule 'Multi stage rule 1'
when
  curr: CurrentTxn(pos in ('9100','01'))
  accumulate ($cct: Transaction(pos == '6100', txnAmt >= 10000, this.cardNumber == curr.cardNumber) over window:time (10m) from entry-point Reference;
    $list: collectList($cct))
  $c: Transaction(this.txnAmt >= (0.9*curr.txnAmt), this.cardNumber == curr.cardNumber) from $list
  $t: Transaction(txnType == 'cardReissue', this before[0h,72h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on mutli-stage rule 1 for ' + curr.getCardNumber());
  insert(cepFraud);
end
