package com.myspace.ceptest;

import fraud.analysis.demo.transaction.Transaction;


declare Transaction @role( event )  @timestamp( txnTS ) end

rule "Fraud TS Stage Rules"
when
    curr: CurrentTxn(pos in ('9100','01'))
    accumulate ($cct: Transaction(pos == '6100', txnAmt>=10000.00, this.cardNumber == curr.cardNumber) over window:time (10m) from entry-point Reference;
    			$list: collectList($cct))
    $c : Transaction(this.txnAmt >= (0.9*curr.txnAmt), this.cardNumber == curr.cardNumber) from $list
    $t: Transaction(txnType == 'cardReissue', this before[0h,72h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference
    
then
CEPFraud cepFraud = new CEPFraud();
        cepFraud.setTransaction(curr);
		cepFraud.setFraudReason("\nRules fired for fraud stage Rules"+curr.getCardNumber());
		insert(cepFraud);

	
end

