package com.myspace.ceptest;
import fraud.analysis.demo.transaction.Transaction;
import fraud.analysis.demo.transaction.CEPFraud;

declare Transaction @role( event )  @timestamp( timestamp ) end

rule "tet"
when
r:Reference()
t:Transaction(this.merchantType==r.merchantType, this.transactionType==r.transactionType) over window:time (1m) from entry-point Reference;
then
CEPFraud cepFraud = new CEPFraud();
cepFraud.setTransaction(t);
cepFraud.setFraudReason("More than 2 txns for Web purchases for the merchant"+r.getTransactionId());
System.out.println("here"+cepFraud.getFraudReason());
insert(cepFraud);
retract(r);
end

