package com.myspace.ceptest;
import fraud.analysis.demo.transaction.Transaction;
import fraud.analysis.demo.transaction.CEPFraud;

declare Transaction @role( event )  @timestamp( timestamp ) end

rule "tet"
when
tn: Transaction()
accumulate ($b:Transaction(this.transactionType == tn.transactionId, this.merchantType==tn.merchantType) over window:time( 1m ) from entry-point Reference;
$number: count($b);$number > 2)
then
CEPFraud cepFraud = new CEPFraud();
cepFraud.setTransaction(tn);
cepFraud.setFraudReason("More than 2 txns for Web purchases for the merchant");
insert(cepFraud);
end

