package com.myspace.ceptest;
import fraud.analysis.demo.transaction.Transaction;
import fraud.analysis.demo.transaction.CEPFraud;

declare Transaction @role( event )  @timestamp( timestamp ) end

rule "tet"
when
accumulate ($cct: Transaction() over window:time (1m) from entry-point Reference;
				$nrOfTransactions : count($cct), 
				$list: collectList($cct);
				$nrOfTransactions >= 4)
	$c1: Transaction() from $list
	$c2: Transaction(this != $c1, this after[0s, 10s] $c1) from $list		
then
CEPFraud cepFraud = new CEPFraud();
cepFraud.setTransaction(tn);
cepFraud.setFraudReason("More than 2 txns for Web purchases for the merchant");
insert(cepFraud);
end

