package com.myspace.ceptest;

rule "Filler Rule 1"
when
  curr: CurrentTxn(merchantType=='EXCLUDE1')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 2"
when
  curr: CurrentTxn(merchantType=='EXCLUDE2')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 3"
when
  curr: CurrentTxn(merchantType=='EXCLUDE3')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 4"
when
  curr: CurrentTxn(merchantType=='EXCLUDE4')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 5"
when
  curr: CurrentTxn(merchantType=='EXCLUDE5')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 6"
when
  curr: CurrentTxn(merchantType=='EXCLUDE6')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 7"
when
  curr: CurrentTxn(merchantType=='EXCLUDE7')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 8"
when
  curr: CurrentTxn(merchantType=='EXCLUDE8')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 9"
when
  curr: CurrentTxn(merchantType=='EXCLUDE9')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 10"
when
  curr: CurrentTxn(merchantType=='EXCLUDE10')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 11"
when
  curr: CurrentTxn(merchantType=='EXCLUDE11')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 12"
when
  curr: CurrentTxn(merchantType=='EXCLUDE12')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 13"
when
  curr: CurrentTxn(merchantType=='EXCLUDE13')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 14"
when
  curr: CurrentTxn(merchantType=='EXCLUDE14')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 15"
when
  curr: CurrentTxn(merchantType=='EXCLUDE15')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 16"
when
  curr: CurrentTxn(merchantType=='EXCLUDE16')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 17"
when
  curr: CurrentTxn(merchantType=='EXCLUDE17')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 18"
when
  curr: CurrentTxn(merchantType=='EXCLUDE18')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 19"
when
  curr: CurrentTxn(merchantType=='EXCLUDE19')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 20"
when
  curr: CurrentTxn(merchantType=='EXCLUDE20')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 21"
when
  curr: CurrentTxn(merchantType=='EXCLUDE21')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 22"
when
  curr: CurrentTxn(merchantType=='EXCLUDE22')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 23"
when
  curr: CurrentTxn(merchantType=='EXCLUDE23')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 24"
when
  curr: CurrentTxn(merchantType=='EXCLUDE24')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 25"
when
  curr: CurrentTxn(merchantType=='EXCLUDE25')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 26"
when
  curr: CurrentTxn(merchantType=='EXCLUDE26')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 27"
when
  curr: CurrentTxn(merchantType=='EXCLUDE27')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 28"
when
  curr: CurrentTxn(merchantType=='EXCLUDE28')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 29"
when
  curr: CurrentTxn(merchantType=='EXCLUDE29')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 30"
when
  curr: CurrentTxn(merchantType=='EXCLUDE30')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 31"
when
  curr: CurrentTxn(merchantType=='EXCLUDE31')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 32"
when
  curr: CurrentTxn(merchantType=='EXCLUDE32')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 33"
when
  curr: CurrentTxn(merchantType=='EXCLUDE33')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 34"
when
  curr: CurrentTxn(merchantType=='EXCLUDE34')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 35"
when
  curr: CurrentTxn(merchantType=='EXCLUDE35')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 36"
when
  curr: CurrentTxn(merchantType=='EXCLUDE36')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 37"
when
  curr: CurrentTxn(merchantType=='EXCLUDE37')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 38"
when
  curr: CurrentTxn(merchantType=='EXCLUDE38')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 39"
when
  curr: CurrentTxn(merchantType=='EXCLUDE39')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 40"
when
  curr: CurrentTxn(merchantType=='EXCLUDE40')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 41"
when
  curr: CurrentTxn(merchantType=='EXCLUDE41')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 42"
when
  curr: CurrentTxn(merchantType=='EXCLUDE42')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 43"
when
  curr: CurrentTxn(merchantType=='EXCLUDE43')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 44"
when
  curr: CurrentTxn(merchantType=='EXCLUDE44')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 45"
when
  curr: CurrentTxn(merchantType=='EXCLUDE45')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 46"
when
  curr: CurrentTxn(merchantType=='EXCLUDE46')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 47"
when
  curr: CurrentTxn(merchantType=='EXCLUDE47')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 48"
when
  curr: CurrentTxn(merchantType=='EXCLUDE48')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 49"
when
  curr: CurrentTxn(merchantType=='EXCLUDE49')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 50"
when
  curr: CurrentTxn(merchantType=='EXCLUDE50')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 51"
when
  curr: CurrentTxn(merchantType=='EXCLUDE51')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 52"
when
  curr: CurrentTxn(merchantType=='EXCLUDE52')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 53"
when
  curr: CurrentTxn(merchantType=='EXCLUDE53')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 54"
when
  curr: CurrentTxn(merchantType=='EXCLUDE54')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 55"
when
  curr: CurrentTxn(merchantType=='EXCLUDE55')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 56"
when
  curr: CurrentTxn(merchantType=='EXCLUDE56')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 57"
when
  curr: CurrentTxn(merchantType=='EXCLUDE57')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 58"
when
  curr: CurrentTxn(merchantType=='EXCLUDE58')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 59"
when
  curr: CurrentTxn(merchantType=='EXCLUDE59')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 60"
when
  curr: CurrentTxn(merchantType=='EXCLUDE60')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 61"
when
  curr: CurrentTxn(merchantType=='EXCLUDE61')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 62"
when
  curr: CurrentTxn(merchantType=='EXCLUDE62')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 63"
when
  curr: CurrentTxn(merchantType=='EXCLUDE63')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 64"
when
  curr: CurrentTxn(merchantType=='EXCLUDE64')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 65"
when
  curr: CurrentTxn(merchantType=='EXCLUDE65')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 66"
when
  curr: CurrentTxn(merchantType=='EXCLUDE66')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 67"
when
  curr: CurrentTxn(merchantType=='EXCLUDE67')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 68"
when
  curr: CurrentTxn(merchantType=='EXCLUDE68')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 69"
when
  curr: CurrentTxn(merchantType=='EXCLUDE69')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 70"
when
  curr: CurrentTxn(merchantType=='EXCLUDE70')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 71"
when
  curr: CurrentTxn(merchantType=='EXCLUDE71')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 72"
when
  curr: CurrentTxn(merchantType=='EXCLUDE72')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 73"
when
  curr: CurrentTxn(merchantType=='EXCLUDE73')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 74"
when
  curr: CurrentTxn(merchantType=='EXCLUDE74')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 75"
when
  curr: CurrentTxn(merchantType=='EXCLUDE75')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 76"
when
  curr: CurrentTxn(merchantType=='EXCLUDE76')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 77"
when
  curr: CurrentTxn(merchantType=='EXCLUDE77')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 78"
when
  curr: CurrentTxn(merchantType=='EXCLUDE78')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 79"
when
  curr: CurrentTxn(merchantType=='EXCLUDE79')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 80"
when
  curr: CurrentTxn(merchantType=='EXCLUDE80')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 81"
when
  curr: CurrentTxn(merchantType=='EXCLUDE81')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 82"
when
  curr: CurrentTxn(merchantType=='EXCLUDE82')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 83"
when
  curr: CurrentTxn(merchantType=='EXCLUDE83')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 84"
when
  curr: CurrentTxn(merchantType=='EXCLUDE84')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 85"
when
  curr: CurrentTxn(merchantType=='EXCLUDE85')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 86"
when
  curr: CurrentTxn(merchantType=='EXCLUDE86')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 87"
when
  curr: CurrentTxn(merchantType=='EXCLUDE87')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 88"
when
  curr: CurrentTxn(merchantType=='EXCLUDE88')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 89"
when
  curr: CurrentTxn(merchantType=='EXCLUDE89')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 90"
when
  curr: CurrentTxn(merchantType=='EXCLUDE90')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 91"
when
  curr: CurrentTxn(merchantType=='EXCLUDE91')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 92"
when
  curr: CurrentTxn(merchantType=='EXCLUDE92')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 93"
when
  curr: CurrentTxn(merchantType=='EXCLUDE93')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 94"
when
  curr: CurrentTxn(merchantType=='EXCLUDE94')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 95"
when
  curr: CurrentTxn(merchantType=='EXCLUDE95')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 96"
when
  curr: CurrentTxn(merchantType=='EXCLUDE96')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 97"
when
  curr: CurrentTxn(merchantType=='EXCLUDE97')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 98"
when
  curr: CurrentTxn(merchantType=='EXCLUDE98')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 99"
when
  curr: CurrentTxn(merchantType=='EXCLUDE99')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 100"
when
  curr: CurrentTxn(merchantType=='EXCLUDE100')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 101"
when
  curr: CurrentTxn(merchantType=='EXCLUDE101')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 102"
when
  curr: CurrentTxn(merchantType=='EXCLUDE102')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 103"
when
  curr: CurrentTxn(merchantType=='EXCLUDE103')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 104"
when
  curr: CurrentTxn(merchantType=='EXCLUDE104')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end