package com.myspace.ceptest;
import fraud.analysis.demo.transaction.*;

rule "Filler Rule 1"
when
  curr: CurrentTxn(merchId=='EXCLUDE1')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 2"
when
  curr: CurrentTxn(merchId=='EXCLUDE2')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 3"
when
  curr: CurrentTxn(merchId=='EXCLUDE3')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 4"
when
  curr: CurrentTxn(merchId=='EXCLUDE4')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 5"
when
  curr: CurrentTxn(merchId=='EXCLUDE5')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 6"
when
  curr: CurrentTxn(merchId=='EXCLUDE6')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 7"
when
  curr: CurrentTxn(merchId=='EXCLUDE7')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 8"
when
  curr: CurrentTxn(merchId=='EXCLUDE8')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 9"
when
  curr: CurrentTxn(merchId=='EXCLUDE9')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 10"
when
  curr: CurrentTxn(merchId=='EXCLUDE10')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 11"
when
  curr: CurrentTxn(merchId=='EXCLUDE11')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 12"
when
  curr: CurrentTxn(merchId=='EXCLUDE12')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 13"
when
  curr: CurrentTxn(merchId=='EXCLUDE13')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 14"
when
  curr: CurrentTxn(merchId=='EXCLUDE14')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 15"
when
  curr: CurrentTxn(merchId=='EXCLUDE15')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 16"
when
  curr: CurrentTxn(merchId=='EXCLUDE16')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 17"
when
  curr: CurrentTxn(merchId=='EXCLUDE17')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 18"
when
  curr: CurrentTxn(merchId=='EXCLUDE18')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 19"
when
  curr: CurrentTxn(merchId=='EXCLUDE19')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 20"
when
  curr: CurrentTxn(merchId=='EXCLUDE20')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 21"
when
  curr: CurrentTxn(merchId=='EXCLUDE21')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 22"
when
  curr: CurrentTxn(merchId=='EXCLUDE22')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 23"
when
  curr: CurrentTxn(merchId=='EXCLUDE23')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 24"
when
  curr: CurrentTxn(merchId=='EXCLUDE24')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 25"
when
  curr: CurrentTxn(merchId=='EXCLUDE25')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 26"
when
  curr: CurrentTxn(merchId=='EXCLUDE26')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 27"
when
  curr: CurrentTxn(merchId=='EXCLUDE27')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 28"
when
  curr: CurrentTxn(merchId=='EXCLUDE28')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 29"
when
  curr: CurrentTxn(merchId=='EXCLUDE29')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 30"
when
  curr: CurrentTxn(merchId=='EXCLUDE30')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 31"
when
  curr: CurrentTxn(merchId=='EXCLUDE31')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 32"
when
  curr: CurrentTxn(merchId=='EXCLUDE32')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 33"
when
  curr: CurrentTxn(merchId=='EXCLUDE33')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 34"
when
  curr: CurrentTxn(merchId=='EXCLUDE34')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 35"
when
  curr: CurrentTxn(merchId=='EXCLUDE35')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 36"
when
  curr: CurrentTxn(merchId=='EXCLUDE36')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 37"
when
  curr: CurrentTxn(merchId=='EXCLUDE37')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 38"
when
  curr: CurrentTxn(merchId=='EXCLUDE38')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 39"
when
  curr: CurrentTxn(merchId=='EXCLUDE39')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 40"
when
  curr: CurrentTxn(merchId=='EXCLUDE40')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 41"
when
  curr: CurrentTxn(merchId=='EXCLUDE41')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 42"
when
  curr: CurrentTxn(merchId=='EXCLUDE42')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 43"
when
  curr: CurrentTxn(merchId=='EXCLUDE43')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 44"
when
  curr: CurrentTxn(merchId=='EXCLUDE44')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 45"
when
  curr: CurrentTxn(merchId=='EXCLUDE45')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 46"
when
  curr: CurrentTxn(merchId=='EXCLUDE46')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 47"
when
  curr: CurrentTxn(merchId=='EXCLUDE47')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 48"
when
  curr: CurrentTxn(merchId=='EXCLUDE48')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 49"
when
  curr: CurrentTxn(merchId=='EXCLUDE49')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 50"
when
  curr: CurrentTxn(merchId=='EXCLUDE50')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 51"
when
  curr: CurrentTxn(merchId=='EXCLUDE51')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 52"
when
  curr: CurrentTxn(merchId=='EXCLUDE52')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 53"
when
  curr: CurrentTxn(merchId=='EXCLUDE53')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 54"
when
  curr: CurrentTxn(merchId=='EXCLUDE54')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 55"
when
  curr: CurrentTxn(merchId=='EXCLUDE55')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 56"
when
  curr: CurrentTxn(merchId=='EXCLUDE56')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 57"
when
  curr: CurrentTxn(merchId=='EXCLUDE57')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 58"
when
  curr: CurrentTxn(merchId=='EXCLUDE58')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 59"
when
  curr: CurrentTxn(merchId=='EXCLUDE59')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 60"
when
  curr: CurrentTxn(merchId=='EXCLUDE60')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 61"
when
  curr: CurrentTxn(merchId=='EXCLUDE61')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 62"
when
  curr: CurrentTxn(merchId=='EXCLUDE62')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 63"
when
  curr: CurrentTxn(merchId=='EXCLUDE63')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 64"
when
  curr: CurrentTxn(merchId=='EXCLUDE64')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 65"
when
  curr: CurrentTxn(merchId=='EXCLUDE65')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 66"
when
  curr: CurrentTxn(merchId=='EXCLUDE66')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 67"
when
  curr: CurrentTxn(merchId=='EXCLUDE67')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 68"
when
  curr: CurrentTxn(merchId=='EXCLUDE68')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 69"
when
  curr: CurrentTxn(merchId=='EXCLUDE69')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 70"
when
  curr: CurrentTxn(merchId=='EXCLUDE70')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 71"
when
  curr: CurrentTxn(merchId=='EXCLUDE71')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 72"
when
  curr: CurrentTxn(merchId=='EXCLUDE72')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 73"
when
  curr: CurrentTxn(merchId=='EXCLUDE73')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 74"
when
  curr: CurrentTxn(merchId=='EXCLUDE74')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 75"
when
  curr: CurrentTxn(merchId=='EXCLUDE75')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 76"
when
  curr: CurrentTxn(merchId=='EXCLUDE76')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 77"
when
  curr: CurrentTxn(merchId=='EXCLUDE77')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 78"
when
  curr: CurrentTxn(merchId=='EXCLUDE78')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 79"
when
  curr: CurrentTxn(merchId=='EXCLUDE79')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 80"
when
  curr: CurrentTxn(merchId=='EXCLUDE80')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 81"
when
  curr: CurrentTxn(merchId=='EXCLUDE81')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 82"
when
  curr: CurrentTxn(merchId=='EXCLUDE82')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 83"
when
  curr: CurrentTxn(merchId=='EXCLUDE83')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 84"
when
  curr: CurrentTxn(merchId=='EXCLUDE84')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 85"
when
  curr: CurrentTxn(merchId=='EXCLUDE85')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 86"
when
  curr: CurrentTxn(merchId=='EXCLUDE86')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 87"
when
  curr: CurrentTxn(merchId=='EXCLUDE87')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 88"
when
  curr: CurrentTxn(merchId=='EXCLUDE88')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 89"
when
  curr: CurrentTxn(merchId=='EXCLUDE89')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 90"
when
  curr: CurrentTxn(merchId=='EXCLUDE90')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 91"
when
  curr: CurrentTxn(merchId=='EXCLUDE91')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 92"
when
  curr: CurrentTxn(merchId=='EXCLUDE92')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 93"
when
  curr: CurrentTxn(merchId=='EXCLUDE93')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 94"
when
  curr: CurrentTxn(merchId=='EXCLUDE94')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 95"
when
  curr: CurrentTxn(merchId=='EXCLUDE95')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 96"
when
  curr: CurrentTxn(merchId=='EXCLUDE96')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 97"
when
  curr: CurrentTxn(merchId=='EXCLUDE97')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 98"
when
  curr: CurrentTxn(merchId=='EXCLUDE98')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 99"
when
  curr: CurrentTxn(merchId=='EXCLUDE99')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 100"
when
  curr: CurrentTxn(merchId=='EXCLUDE100')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 101"
when
  curr: CurrentTxn(merchId=='EXCLUDE101')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 102"
when
  curr: CurrentTxn(merchId=='EXCLUDE102')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 103"
when
  curr: CurrentTxn(merchId=='EXCLUDE103')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Filler Rule 104"
when
  curr: CurrentTxn(merchId=='EXCLUDE104')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end