package com.myspace.ceptest;


import fraud.analysis.demo.transaction.Transaction;


declare Transaction @role( event )  @timestamp( txnTS ) end

rule "Profile-Rules"
when
    curr: CurrentTxn(txnType=='ATM')
    accumulate ($cct: Transaction() over window:time (1440h) from entry-point Reference;
    			$list: collectList($cct))
    accumulate($cct: Transaction() over window:time (1440m) from $list;
                $addNos: count($cct.getTxnAmt())
                variance($addNos, curr.getTxnAmt()) >= 150)
then
	System.out.println("\nRules fired for Profile Rules");
	
end
