package com.myspace.ceptest;

import fraud.analysis.demo.transaction.Transaction;


declare Transaction @role( event )  @timestamp( txnTS ) end

rule "Profile-Rules"
when
    curr: CurrentTxn(txnType=='POS')
    
    $addAmt: Number() from  accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24h) from entry-point Reference;
    			sum($ct.getTxnAmt()))
    			
    $c: Transaction(this.cardNumber == curr.cardNumber) from entry-point Reference
    accumulate(t: Transaction(this before[0h,24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference ;
                $addAmtAvg: sum(t.getTxnAmt());
                $addAmtAvg <= 1.5* $addAmt )
    
   
    
then
	System.out.println("\nRules fired for Profile Rules");
	
end
