package com.myspace.ceptest;

import fraud.analysis.demo.transaction.Transaction;
declare Transaction @role( event )  @timestamp( txnTS ) end
rule 'Profile rule for ATM 1'
when
  curr: CurrentTxn(pos in ('ATM'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 1 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for POS 2'
when
  curr: CurrentTxn(pos in ('POS'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 2 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for WEB 3'
when
  curr: CurrentTxn(pos in ('WEB'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 3 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for ATM 4'
when
  curr: CurrentTxn(pos in ('ATM'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 4 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for POS 5'
when
  curr: CurrentTxn(pos in ('POS'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 5 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for WEB 6'
when
  curr: CurrentTxn(pos in ('WEB'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 6 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for ATM 7'
when
  curr: CurrentTxn(pos in ('ATM'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 1.75 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 7 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for POS 8'
when
  curr: CurrentTxn(pos in ('POS'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 1.75 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 8 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for WEB 9'
when
  curr: CurrentTxn(pos in ('WEB'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 1.75 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 9 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for ATM 10'
when
  curr: CurrentTxn(pos in ('ATM'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 1.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 10 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for POS 11'
when
  curr: CurrentTxn(pos in ('POS'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 1.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 11 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for WEB 12'
when
  curr: CurrentTxn(pos in ('WEB'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (24m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 24h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 1.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 12 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for ATM 13'
when
  curr: CurrentTxn(pos in ('ATM'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (48m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 48h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 13 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for POS 14'
when
  curr: CurrentTxn(pos in ('POS'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (48m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 48h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 14 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for WEB 15'
when
  curr: CurrentTxn(pos in ('WEB'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (48m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 48h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2.5 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 15 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for ATM 16'
when
  curr: CurrentTxn(pos in ('ATM'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (48m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 48h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 16 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for POS 17'
when
  curr: CurrentTxn(pos in ('POS'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (48m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 48h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 17 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for WEB 18'
when
  curr: CurrentTxn(pos in ('WEB'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (48m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 48h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 2 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 18 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for ATM 19'
when
  curr: CurrentTxn(pos in ('ATM'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (48m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 48h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 1.75 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 19 for ' + curr.getCardNumber());
  insert(cepFraud);
end
rule 'Profile rule for POS 20'
when
  curr: CurrentTxn(pos in ('POS'))
  $addAmt: Number() from accumulate ($ct: Transaction(this.cardNumber == curr.cardNumber) over window:time (48m) from entry-point Reference;
    sum($ct.getTxnAmt()))
  $c: Transaction(this.cardNumber == curr.cardNumber, (new java.util.Date().getTime() - this.txnTS) > 864000000) from entry-point Reference

  accumulate(t: Transaction(this before[0h, 48h] $c, this.cardNumber == curr.cardNumber) over window:time (1440m) from entry-point Reference;
    $addAmtAvg: sum(t.getTxnAmt());
    $addAmtAvg <= 1.75 * $addAmt)
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('Flagged tx based on profile rule 20 for ' + curr.getCardNumber());
  insert(cepFraud);
end

