package com.myspace.ceptest;

declare Transaction @role( event )  @timestamp( txnTS ) end
rule '1 and 2: Same type transaction rule - sum of tx 1'
when
  curr: CurrentTxn(pos in ('9100','01'))
  accumulate ($cct: Transaction(pos in ('9100','01'), curr.merchId == this.merchId, this.txnAmt == curr.txnAmt, this.cardNumber == curr.cardNumber) over window:time (1415m) from entry-point Reference;
    $nrOfTransactions : count($cct),
    $sumOfTransactions : sum($cct.getTxnAmt()))
  if ($nrOfTransactions > 5) do[count]
  if ($sumOfTransactions >= 1000) do[sum]
then[sum]
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('2: sum of tx - Flagged tx based on same-tx rule 1 for ' + curr.getCardNumber());
  insert(cepFraud);
then[count]
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('1: num of tx - Flagged tx based on same-tx rule 1 for ' + curr.getCardNumber());
  insert(cepFraud);
end