package com.myspace.ceptest;

import fraud.analysis.demo.transaction.*;
rule "Txn Type Filler Rule 1"
when
  curr: CurrentTxn(txnType=='EXCLUDE1')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 2"
when
  curr: CurrentTxn(txnType=='EXCLUDE2')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 3"
when
  curr: CurrentTxn(txnType=='EXCLUDE3')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 4"
when
  curr: CurrentTxn(txnType=='EXCLUDE4')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 5"
when
  curr: CurrentTxn(txnType=='EXCLUDE5')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 6"
when
  curr: CurrentTxn(txnType=='EXCLUDE6')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 7"
when
  curr: CurrentTxn(txnType=='EXCLUDE7')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 8"
when
  curr: CurrentTxn(txnType=='EXCLUDE8')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 9"
when
  curr: CurrentTxn(txnType=='EXCLUDE9')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 10"
when
  curr: CurrentTxn(txnType=='EXCLUDE10')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 11"
when
  curr: CurrentTxn(txnType=='EXCLUDE11')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 12"
when
  curr: CurrentTxn(txnType=='EXCLUDE12')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 13"
when
  curr: CurrentTxn(txnType=='EXCLUDE13')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 14"
when
  curr: CurrentTxn(txnType=='EXCLUDE14')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 15"
when
  curr: CurrentTxn(txnType=='EXCLUDE15')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 16"
when
  curr: CurrentTxn(txnType=='EXCLUDE16')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 17"
when
  curr: CurrentTxn(txnType=='EXCLUDE17')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 18"
when
  curr: CurrentTxn(txnType=='EXCLUDE18')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 19"
when
  curr: CurrentTxn(txnType=='EXCLUDE19')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 20"
when
  curr: CurrentTxn(txnType=='EXCLUDE20')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 21"
when
  curr: CurrentTxn(txnType=='EXCLUDE21')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 22"
when
  curr: CurrentTxn(txnType=='EXCLUDE22')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 23"
when
  curr: CurrentTxn(txnType=='EXCLUDE23')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 24"
when
  curr: CurrentTxn(txnType=='EXCLUDE24')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 25"
when
  curr: CurrentTxn(txnType=='EXCLUDE25')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 26"
when
  curr: CurrentTxn(txnType=='EXCLUDE26')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 27"
when
  curr: CurrentTxn(txnType=='EXCLUDE27')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 28"
when
  curr: CurrentTxn(txnType=='EXCLUDE28')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 29"
when
  curr: CurrentTxn(txnType=='EXCLUDE29')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 30"
when
  curr: CurrentTxn(txnType=='EXCLUDE30')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 31"
when
  curr: CurrentTxn(txnType=='EXCLUDE31')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 32"
when
  curr: CurrentTxn(txnType=='EXCLUDE32')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 33"
when
  curr: CurrentTxn(txnType=='EXCLUDE33')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 34"
when
  curr: CurrentTxn(txnType=='EXCLUDE34')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 35"
when
  curr: CurrentTxn(txnType=='EXCLUDE35')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 36"
when
  curr: CurrentTxn(txnType=='EXCLUDE36')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 37"
when
  curr: CurrentTxn(txnType=='EXCLUDE37')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 38"
when
  curr: CurrentTxn(txnType=='EXCLUDE38')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 39"
when
  curr: CurrentTxn(txnType=='EXCLUDE39')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 40"
when
  curr: CurrentTxn(txnType=='EXCLUDE40')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 41"
when
  curr: CurrentTxn(txnType=='EXCLUDE41')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 42"
when
  curr: CurrentTxn(txnType=='EXCLUDE42')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 43"
when
  curr: CurrentTxn(txnType=='EXCLUDE43')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 44"
when
  curr: CurrentTxn(txnType=='EXCLUDE44')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 45"
when
  curr: CurrentTxn(txnType=='EXCLUDE45')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 46"
when
  curr: CurrentTxn(txnType=='EXCLUDE46')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 47"
when
  curr: CurrentTxn(txnType=='EXCLUDE47')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 48"
when
  curr: CurrentTxn(txnType=='EXCLUDE48')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 49"
when
  curr: CurrentTxn(txnType=='EXCLUDE49')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 50"
when
  curr: CurrentTxn(txnType=='EXCLUDE50')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 51"
when
  curr: CurrentTxn(txnType=='EXCLUDE51')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 52"
when
  curr: CurrentTxn(txnType=='EXCLUDE52')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 53"
when
  curr: CurrentTxn(txnType=='EXCLUDE53')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 54"
when
  curr: CurrentTxn(txnType=='EXCLUDE54')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 55"
when
  curr: CurrentTxn(txnType=='EXCLUDE55')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 56"
when
  curr: CurrentTxn(txnType=='EXCLUDE56')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 57"
when
  curr: CurrentTxn(txnType=='EXCLUDE57')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 58"
when
  curr: CurrentTxn(txnType=='EXCLUDE58')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 59"
when
  curr: CurrentTxn(txnType=='EXCLUDE59')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 60"
when
  curr: CurrentTxn(txnType=='EXCLUDE60')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 61"
when
  curr: CurrentTxn(txnType=='EXCLUDE61')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 62"
when
  curr: CurrentTxn(txnType=='EXCLUDE62')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 63"
when
  curr: CurrentTxn(txnType=='EXCLUDE63')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 64"
when
  curr: CurrentTxn(txnType=='EXCLUDE64')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 65"
when
  curr: CurrentTxn(txnType=='EXCLUDE65')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 66"
when
  curr: CurrentTxn(txnType=='EXCLUDE66')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 67"
when
  curr: CurrentTxn(txnType=='EXCLUDE67')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 68"
when
  curr: CurrentTxn(txnType=='EXCLUDE68')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 69"
when
  curr: CurrentTxn(txnType=='EXCLUDE69')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 70"
when
  curr: CurrentTxn(txnType=='EXCLUDE70')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 71"
when
  curr: CurrentTxn(txnType=='EXCLUDE71')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 72"
when
  curr: CurrentTxn(txnType=='EXCLUDE72')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 73"
when
  curr: CurrentTxn(txnType=='EXCLUDE73')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 74"
when
  curr: CurrentTxn(txnType=='EXCLUDE74')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 75"
when
  curr: CurrentTxn(txnType=='EXCLUDE75')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 76"
when
  curr: CurrentTxn(txnType=='EXCLUDE76')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 77"
when
  curr: CurrentTxn(txnType=='EXCLUDE77')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 78"
when
  curr: CurrentTxn(txnType=='EXCLUDE78')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 79"
when
  curr: CurrentTxn(txnType=='EXCLUDE79')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 80"
when
  curr: CurrentTxn(txnType=='EXCLUDE80')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 81"
when
  curr: CurrentTxn(txnType=='EXCLUDE81')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 82"
when
  curr: CurrentTxn(txnType=='EXCLUDE82')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 83"
when
  curr: CurrentTxn(txnType=='EXCLUDE83')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 84"
when
  curr: CurrentTxn(txnType=='EXCLUDE84')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 85"
when
  curr: CurrentTxn(txnType=='EXCLUDE85')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 86"
when
  curr: CurrentTxn(txnType=='EXCLUDE86')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 87"
when
  curr: CurrentTxn(txnType=='EXCLUDE87')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 88"
when
  curr: CurrentTxn(txnType=='EXCLUDE88')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 89"
when
  curr: CurrentTxn(txnType=='EXCLUDE89')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 90"
when
  curr: CurrentTxn(txnType=='EXCLUDE90')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 91"
when
  curr: CurrentTxn(txnType=='EXCLUDE91')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 92"
when
  curr: CurrentTxn(txnType=='EXCLUDE92')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 93"
when
  curr: CurrentTxn(txnType=='EXCLUDE93')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 94"
when
  curr: CurrentTxn(txnType=='EXCLUDE94')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 95"
when
  curr: CurrentTxn(txnType=='EXCLUDE95')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 96"
when
  curr: CurrentTxn(txnType=='EXCLUDE96')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 97"
when
  curr: CurrentTxn(txnType=='EXCLUDE97')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 98"
when
  curr: CurrentTxn(txnType=='EXCLUDE98')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 99"
when
  curr: CurrentTxn(txnType=='EXCLUDE99')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 100"
when
  curr: CurrentTxn(txnType=='EXCLUDE100')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 101"
when
  curr: CurrentTxn(txnType=='EXCLUDE101')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 102"
when
  curr: CurrentTxn(txnType=='EXCLUDE102')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 103"
when
  curr: CurrentTxn(txnType=='EXCLUDE103')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
  end
  
rule "Txn Type Filler Rule 104"
when
  curr: CurrentTxn(txnType=='EXCLUDE104')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end


rule "Txn Type Filler Rule 105"
when
  curr: CurrentTxn(txnType=='EXCLUDE105')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 106"
when
  curr: CurrentTxn(txnType=='EXCLUDE106')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 107"
when
  curr: CurrentTxn(txnType=='EXCLUDE107')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 108"
when
  curr: CurrentTxn(txnType=='EXCLUDE108')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 109"
when
  curr: CurrentTxn(txnType=='EXCLUDE109')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 110"
when
  curr: CurrentTxn(txnType=='EXCLUDE110')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 111"
when
  curr: CurrentTxn(txnType=='EXCLUDE111')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 112"
when
  curr: CurrentTxn(txnType=='EXCLUDE112')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 113"
when
  curr: CurrentTxn(txnType=='EXCLUDE113')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 114"
when
  curr: CurrentTxn(txnType=='EXCLUDE114')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 115"
when
  curr: CurrentTxn(txnType=='EXCLUDE115')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 116"
when
  curr: CurrentTxn(txnType=='EXCLUDE116')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 117"
when
  curr: CurrentTxn(txnType=='EXCLUDE117')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 118"
when
  curr: CurrentTxn(txnType=='EXCLUDE118')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 119"
when
  curr: CurrentTxn(txnType=='EXCLUDE119')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 120"
when
  curr: CurrentTxn(txnType=='EXCLUDE120')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 121"
when
  curr: CurrentTxn(txnType=='EXCLUDE121')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 122"
when
  curr: CurrentTxn(txnType=='EXCLUDE122')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 123"
when
  curr: CurrentTxn(txnType=='EXCLUDE123')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 124"
when
  curr: CurrentTxn(txnType=='EXCLUDE124')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 125"
when
  curr: CurrentTxn(txnType=='EXCLUDE125')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 126"
when
  curr: CurrentTxn(txnType=='EXCLUDE126')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 127"
when
  curr: CurrentTxn(txnType=='EXCLUDE127')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 128"
when
  curr: CurrentTxn(txnType=='EXCLUDE128')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 129"
when
  curr: CurrentTxn(txnType=='EXCLUDE129')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 130"
when
  curr: CurrentTxn(txnType=='EXCLUDE130')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 131"
when
  curr: CurrentTxn(txnType=='EXCLUDE131')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 132"
when
  curr: CurrentTxn(txnType=='EXCLUDE132')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 133"
when
  curr: CurrentTxn(txnType=='EXCLUDE133')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 134"
when
  curr: CurrentTxn(txnType=='EXCLUDE134')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 135"
when
  curr: CurrentTxn(txnType=='EXCLUDE135')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 136"
when
  curr: CurrentTxn(txnType=='EXCLUDE136')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 137"
when
  curr: CurrentTxn(txnType=='EXCLUDE137')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 138"
when
  curr: CurrentTxn(txnType=='EXCLUDE138')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 139"
when
  curr: CurrentTxn(txnType=='EXCLUDE139')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 140"
when
  curr: CurrentTxn(txnType=='EXCLUDE140')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 141"
when
  curr: CurrentTxn(txnType=='EXCLUDE141')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 142"
when
  curr: CurrentTxn(txnType=='EXCLUDE142')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 143"
when
  curr: CurrentTxn(txnType=='EXCLUDE143')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 144"
when
  curr: CurrentTxn(txnType=='EXCLUDE144')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 145"
when
  curr: CurrentTxn(txnType=='EXCLUDE145')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 146"
when
  curr: CurrentTxn(txnType=='EXCLUDE146')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 147"
when
  curr: CurrentTxn(txnType=='EXCLUDE147')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 148"
when
  curr: CurrentTxn(txnType=='EXCLUDE148')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 149"
when
  curr: CurrentTxn(txnType=='EXCLUDE149')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 150"
when
  curr: CurrentTxn(txnType=='EXCLUDE150')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 151"
when
  curr: CurrentTxn(txnType=='EXCLUDE151')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 152"
when
  curr: CurrentTxn(txnType=='EXCLUDE152')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 153"
when
  curr: CurrentTxn(txnType=='EXCLUDE153')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 154"
when
  curr: CurrentTxn(txnType=='EXCLUDE154')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 155"
when
  curr: CurrentTxn(txnType=='EXCLUDE155')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 156"
when
  curr: CurrentTxn(txnType=='EXCLUDE156')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 157"
when
  curr: CurrentTxn(txnType=='EXCLUDE157')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 158"
when
  curr: CurrentTxn(txnType=='EXCLUDE158')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 159"
when
  curr: CurrentTxn(txnType=='EXCLUDE159')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 160"
when
  curr: CurrentTxn(txnType=='EXCLUDE160')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 161"
when
  curr: CurrentTxn(txnType=='EXCLUDE161')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 162"
when
  curr: CurrentTxn(txnType=='EXCLUDE162')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 163"
when
  curr: CurrentTxn(txnType=='EXCLUDE163')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 164"
when
  curr: CurrentTxn(txnType=='EXCLUDE164')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 165"
when
  curr: CurrentTxn(txnType=='EXCLUDE165')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 166"
when
  curr: CurrentTxn(txnType=='EXCLUDE166')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 167"
when
  curr: CurrentTxn(txnType=='EXCLUDE167')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 168"
when
  curr: CurrentTxn(txnType=='EXCLUDE168')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 169"
when
  curr: CurrentTxn(txnType=='EXCLUDE169')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 170"
when
  curr: CurrentTxn(txnType=='EXCLUDE170')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 171"
when
  curr: CurrentTxn(txnType=='EXCLUDE171')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 172"
when
  curr: CurrentTxn(txnType=='EXCLUDE172')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 173"
when
  curr: CurrentTxn(txnType=='EXCLUDE173')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 174"
when
  curr: CurrentTxn(txnType=='EXCLUDE174')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 175"
when
  curr: CurrentTxn(txnType=='EXCLUDE175')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 176"
when
  curr: CurrentTxn(txnType=='EXCLUDE176')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 177"
when
  curr: CurrentTxn(txnType=='EXCLUDE177')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 178"
when
  curr: CurrentTxn(txnType=='EXCLUDE178')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 179"
when
  curr: CurrentTxn(txnType=='EXCLUDE179')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 180"
when
  curr: CurrentTxn(txnType=='EXCLUDE180')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 181"
when
  curr: CurrentTxn(txnType=='EXCLUDE181')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 182"
when
  curr: CurrentTxn(txnType=='EXCLUDE182')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 183"
when
  curr: CurrentTxn(txnType=='EXCLUDE183')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 184"
when
  curr: CurrentTxn(txnType=='EXCLUDE184')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 185"
when
  curr: CurrentTxn(txnType=='EXCLUDE185')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 186"
when
  curr: CurrentTxn(txnType=='EXCLUDE186')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 187"
when
  curr: CurrentTxn(txnType=='EXCLUDE187')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 188"
when
  curr: CurrentTxn(txnType=='EXCLUDE188')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 189"
when
  curr: CurrentTxn(txnType=='EXCLUDE189')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 190"
when
  curr: CurrentTxn(txnType=='EXCLUDE190')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 191"
when
  curr: CurrentTxn(txnType=='EXCLUDE191')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 192"
when
  curr: CurrentTxn(txnType=='EXCLUDE192')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 193"
when
  curr: CurrentTxn(txnType=='EXCLUDE193')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 194"
when
  curr: CurrentTxn(txnType=='EXCLUDE194')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 195"
when
  curr: CurrentTxn(txnType=='EXCLUDE195')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 196"
when
  curr: CurrentTxn(txnType=='EXCLUDE196')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 197"
when
  curr: CurrentTxn(txnType=='EXCLUDE197')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end