package com.myspace.ceptest;

import fraud.analysis.demo.transaction.*;
rule "Txn Type Filler Rule 1"
when
  curr: CurrentTxn(txnType=='EXCLUDE1')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 2"
when
  curr: CurrentTxn(txnType=='EXCLUDE2')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 3"
when
  curr: CurrentTxn(txnType=='EXCLUDE3')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 4"
when
  curr: CurrentTxn(txnType=='EXCLUDE4')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 5"
when
  curr: CurrentTxn(txnType=='EXCLUDE5')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 6"
when
  curr: CurrentTxn(txnType=='EXCLUDE6')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 7"
when
  curr: CurrentTxn(txnType=='EXCLUDE7')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 8"
when
  curr: CurrentTxn(txnType=='EXCLUDE8')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 9"
when
  curr: CurrentTxn(txnType=='EXCLUDE9')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 10"
when
  curr: CurrentTxn(txnType=='EXCLUDE10')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 11"
when
  curr: CurrentTxn(txnType=='EXCLUDE11')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 12"
when
  curr: CurrentTxn(txnType=='EXCLUDE12')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 13"
when
  curr: CurrentTxn(txnType=='EXCLUDE13')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 14"
when
  curr: CurrentTxn(txnType=='EXCLUDE14')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 15"
when
  curr: CurrentTxn(txnType=='EXCLUDE15')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 16"
when
  curr: CurrentTxn(txnType=='EXCLUDE16')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 17"
when
  curr: CurrentTxn(txnType=='EXCLUDE17')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 18"
when
  curr: CurrentTxn(txnType=='EXCLUDE18')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 19"
when
  curr: CurrentTxn(txnType=='EXCLUDE19')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 20"
when
  curr: CurrentTxn(txnType=='EXCLUDE20')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 21"
when
  curr: CurrentTxn(txnType=='EXCLUDE21')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 22"
when
  curr: CurrentTxn(txnType=='EXCLUDE22')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 23"
when
  curr: CurrentTxn(txnType=='EXCLUDE23')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 24"
when
  curr: CurrentTxn(txnType=='EXCLUDE24')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 25"
when
  curr: CurrentTxn(txnType=='EXCLUDE25')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 26"
when
  curr: CurrentTxn(txnType=='EXCLUDE26')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 27"
when
  curr: CurrentTxn(txnType=='EXCLUDE27')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 28"
when
  curr: CurrentTxn(txnType=='EXCLUDE28')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 29"
when
  curr: CurrentTxn(txnType=='EXCLUDE29')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 30"
when
  curr: CurrentTxn(txnType=='EXCLUDE30')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 31"
when
  curr: CurrentTxn(txnType=='EXCLUDE31')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 32"
when
  curr: CurrentTxn(txnType=='EXCLUDE32')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 33"
when
  curr: CurrentTxn(txnType=='EXCLUDE33')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 34"
when
  curr: CurrentTxn(txnType=='EXCLUDE34')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 35"
when
  curr: CurrentTxn(txnType=='EXCLUDE35')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 36"
when
  curr: CurrentTxn(txnType=='EXCLUDE36')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 37"
when
  curr: CurrentTxn(txnType=='EXCLUDE37')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 38"
when
  curr: CurrentTxn(txnType=='EXCLUDE38')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 39"
when
  curr: CurrentTxn(txnType=='EXCLUDE39')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 40"
when
  curr: CurrentTxn(txnType=='EXCLUDE40')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 41"
when
  curr: CurrentTxn(txnType=='EXCLUDE41')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 42"
when
  curr: CurrentTxn(txnType=='EXCLUDE42')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 43"
when
  curr: CurrentTxn(txnType=='EXCLUDE43')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 44"
when
  curr: CurrentTxn(txnType=='EXCLUDE44')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 45"
when
  curr: CurrentTxn(txnType=='EXCLUDE45')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 46"
when
  curr: CurrentTxn(txnType=='EXCLUDE46')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 47"
when
  curr: CurrentTxn(txnType=='EXCLUDE47')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 48"
when
  curr: CurrentTxn(txnType=='EXCLUDE48')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 49"
when
  curr: CurrentTxn(txnType=='EXCLUDE49')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 50"
when
  curr: CurrentTxn(txnType=='EXCLUDE50')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 51"
when
  curr: CurrentTxn(txnType=='EXCLUDE51')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 52"
when
  curr: CurrentTxn(txnType=='EXCLUDE52')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 53"
when
  curr: CurrentTxn(txnType=='EXCLUDE53')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 54"
when
  curr: CurrentTxn(txnType=='EXCLUDE54')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 55"
when
  curr: CurrentTxn(txnType=='EXCLUDE55')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 56"
when
  curr: CurrentTxn(txnType=='EXCLUDE56')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 57"
when
  curr: CurrentTxn(txnType=='EXCLUDE57')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 58"
when
  curr: CurrentTxn(txnType=='EXCLUDE58')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 59"
when
  curr: CurrentTxn(txnType=='EXCLUDE59')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 60"
when
  curr: CurrentTxn(txnType=='EXCLUDE60')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 61"
when
  curr: CurrentTxn(txnType=='EXCLUDE61')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 62"
when
  curr: CurrentTxn(txnType=='EXCLUDE62')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 63"
when
  curr: CurrentTxn(txnType=='EXCLUDE63')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 64"
when
  curr: CurrentTxn(txnType=='EXCLUDE64')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 65"
when
  curr: CurrentTxn(txnType=='EXCLUDE65')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 66"
when
  curr: CurrentTxn(txnType=='EXCLUDE66')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 67"
when
  curr: CurrentTxn(txnType=='EXCLUDE67')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 68"
when
  curr: CurrentTxn(txnType=='EXCLUDE68')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 69"
when
  curr: CurrentTxn(txnType=='EXCLUDE69')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 70"
when
  curr: CurrentTxn(txnType=='EXCLUDE70')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 71"
when
  curr: CurrentTxn(txnType=='EXCLUDE71')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 72"
when
  curr: CurrentTxn(txnType=='EXCLUDE72')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 73"
when
  curr: CurrentTxn(txnType=='EXCLUDE73')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 74"
when
  curr: CurrentTxn(txnType=='EXCLUDE74')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 75"
when
  curr: CurrentTxn(txnType=='EXCLUDE75')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 76"
when
  curr: CurrentTxn(txnType=='EXCLUDE76')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 77"
when
  curr: CurrentTxn(txnType=='EXCLUDE77')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 78"
when
  curr: CurrentTxn(txnType=='EXCLUDE78')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 79"
when
  curr: CurrentTxn(txnType=='EXCLUDE79')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 80"
when
  curr: CurrentTxn(txnType=='EXCLUDE80')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 81"
when
  curr: CurrentTxn(txnType=='EXCLUDE81')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 82"
when
  curr: CurrentTxn(txnType=='EXCLUDE82')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 83"
when
  curr: CurrentTxn(txnType=='EXCLUDE83')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 84"
when
  curr: CurrentTxn(txnType=='EXCLUDE84')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 85"
when
  curr: CurrentTxn(txnType=='EXCLUDE85')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 86"
when
  curr: CurrentTxn(txnType=='EXCLUDE86')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 87"
when
  curr: CurrentTxn(txnType=='EXCLUDE87')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 88"
when
  curr: CurrentTxn(txnType=='EXCLUDE88')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 89"
when
  curr: CurrentTxn(txnType=='EXCLUDE89')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 90"
when
  curr: CurrentTxn(txnType=='EXCLUDE90')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 91"
when
  curr: CurrentTxn(txnType=='EXCLUDE91')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 92"
when
  curr: CurrentTxn(txnType=='EXCLUDE92')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 93"
when
  curr: CurrentTxn(txnType=='EXCLUDE93')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 94"
when
  curr: CurrentTxn(txnType=='EXCLUDE94')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 95"
when
  curr: CurrentTxn(txnType=='EXCLUDE95')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 96"
when
  curr: CurrentTxn(txnType=='EXCLUDE96')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 97"
when
  curr: CurrentTxn(txnType=='EXCLUDE97')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 98"
when
  curr: CurrentTxn(txnType=='EXCLUDE98')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 99"
when
  curr: CurrentTxn(txnType=='EXCLUDE99')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 100"
when
  curr: CurrentTxn(txnType=='EXCLUDE100')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 101"
when
  curr: CurrentTxn(txnType=='EXCLUDE101')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 102"
when
  curr: CurrentTxn(txnType=='EXCLUDE102')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end
rule "Txn Type Filler Rule 103"
when
  curr: CurrentTxn(txnType=='EXCLUDE103')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
rule "Txn Type Filler Rule 104"
when
  curr: CurrentTxn(txnType=='EXCLUDE104')
 
then
  CEPFraud cepFraud = new CEPFraud();
  cepFraud.setTransactionId(curr.getTransactionId());
  cepFraud.setFraudReason('excluded ' + curr.getCardNumber());
  insert(cepFraud);
end