package com.myspace.ceptest;


import fraud.analysis.demo.transaction.*;


declare Transaction @role( event )  @timestamp( txnTS ) end

rule "Velocity Rules"
when
    curr: CurrentTxn()
    accumulate ($cct: Transaction(txnCntry!='SG', this.cardNumber == curr.cardNumber) over window:time (1415m) from entry-point Reference;
				$nrOfTransactions : count($cct),
				$sumOfTransactions : sum($cct.getTxnAmt()),
				$list: collectList($cct);
				$nrOfTransactions >= 5,
				$sumOfTransactions >= 1000)
	$t: Transaction(this.cardNumber == curr.cardNumber) from $cct
then
	System.out.println("\nRules fired for Velocity Rules for"+curr.getTransactionId());
	retract(curr);
	
end

