package com.myspace.ceptest;
import fraud.analysis.demo.transaction.*;

rule "rule1"

when
curr: CurrentTxn(txnType=="ignore1")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		
		

rule "rule2"		
		when
curr: CurrentTxn(txnType=="ignore2")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		

rule "rule3"		
		when
curr: CurrentTxn(txnType=="ignore3")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		

rule "rule4"		
		when
curr: CurrentTxn(txnType=="ignore4")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		

rule "rule5"		
		when
curr: CurrentTxn(txnType=="ignore5")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		

rule "rule6"		
		when
curr: CurrentTxn(txnType=="ignore6")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		

rule "rule7"		
		when
curr: CurrentTxn(txnType=="ignore7")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "rule8"		
		when
curr: CurrentTxn(txnType=="ignore8")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		

rule "rule9"		
		when
curr: CurrentTxn(txnType=="ignore9")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "rule10"		
		when
curr: CurrentTxn(txnType=="ignore10")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "rule11"		
		when
curr: CurrentTxn(txnType=="ignore11")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		

rule "rule12"		
		when
curr: CurrentTxn(txnType=="ignore12")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "rule13"		
		
		when
curr: CurrentTxn(txnType=="ignore13")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "rule14"		
		when
curr: CurrentTxn(txnType=="ignore14")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "rule15"		
		when
curr: CurrentTxn(txnType=="ignore15")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "rule16"		
		when
curr: CurrentTxn(txnType=="ignore16")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "rule17"		
		when
curr: CurrentTxn(txnType=="ignore17")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		

rule "rule18"		
		when
curr: CurrentTxn(txnType=="ignore18")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end

rule "ignore19"		
		when
curr: CurrentTxn(txnType=="ignore19")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore20"			
		when
curr: CurrentTxn(txnType=="ignore20")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		
rule "ignore21"			
		when
curr: CurrentTxn(txnType=="ignore21")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		
rule "ignore22"			
		when
curr: CurrentTxn(txnType=="ignore22")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore23"			
		
		when
curr: CurrentTxn(txnType=="ignore23")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore24"			
		
		when
curr: CurrentTxn(txnType=="ignore24")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		
rule "ignore25"			
		when
curr: CurrentTxn(txnType=="ignore25")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore26"			
		when
curr: CurrentTxn(txnType=="ignore26")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore27"			
		when
curr: CurrentTxn(txnType=="ignore27")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore28"			
		when
curr: CurrentTxn(txnType=="ignore28")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore29"			
		when
curr: CurrentTxn(txnType=="ignore29")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore30"			
		when
curr: CurrentTxn(txnType=="ignore30")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore31"			
		when
curr: CurrentTxn(txnType=="ignore31")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore32"			
		when
curr: CurrentTxn(txnType=="ignore32")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore33"			
		when
curr: CurrentTxn(txnType=="ignore33")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore34"			
		when
curr: CurrentTxn(txnType=="ignore34")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore35"			
		when
curr: CurrentTxn(txnType=="ignore35")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore36"			
		when
curr: CurrentTxn(txnType=="ignore36")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore37"			
		when
curr: CurrentTxn(txnType=="ignore37")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore38"			
		
		when
curr: CurrentTxn(txnType=="ignore39")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore39"			
		when
curr: CurrentTxn(txnType=="ignore40")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore40"			
		
		when
curr: CurrentTxn(txnType=="ignore41")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore41"			
		when
curr: CurrentTxn(txnType=="ignore42")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore42"			
		when
curr: CurrentTxn(txnType=="ignore43")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore43"			
		when
curr: CurrentTxn(txnType=="ignore44")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore44"			
		when
curr: CurrentTxn(txnType=="ignore46")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
rule "ignore45"			
		when
curr: CurrentTxn(txnType=="ignore47")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
	rule "ignore46"		
		when
curr: CurrentTxn(txnType=="ignore48")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
	rule "ignore47"		
		when
curr: CurrentTxn(txnType=="ignore49")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore48"			
		when
curr: CurrentTxn(txnType=="ignore50")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore49"			
		when
curr: CurrentTxn(txnType=="ignore51")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
	rule "ignore50"				
		when
curr: CurrentTxn(txnType=="ignore52")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore51"			
		when
curr: CurrentTxn(txnType=="ignore53")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore52"			
		
		when
curr: CurrentTxn(txnType=="ignore54")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
	rule "ignore53"				
		when
curr: CurrentTxn(txnType=="ignore55")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore54"			
		when
curr: CurrentTxn(txnType=="ignore56")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore55"			
		when
curr: CurrentTxn(txnType=="ignore57")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
	rule "ignore56"				
		when
curr: CurrentTxn(txnType=="ignore58")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore57"			
		when
curr: CurrentTxn(txnType=="ignore59")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore58"			
		when
curr: CurrentTxn(txnType=="ignore60")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore59"			
		when
curr: CurrentTxn(txnType=="ignore61")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		rule "ignore60"			
		when
curr: CurrentTxn(txnType=="ignore62")
then
	 CEPFraud cepFraud = new CEPFraud();
         cepFraud.setTransactionId(curr.getTransactionId());
		cepFraud.setFraudReason("\nRules fired for Profile Rules for ignore"+curr.getCardNumber());
		insert(cepFraud);
		end
		
		