package com.myspace.ceptest;


import fraud.analysis.demo.transaction.Transaction;
import fraud.analysis.demo.transaction.CEPFraud;

declare Transaction @role( event )  @timestamp( timestamp ) end

rule "sdfsf"
when


accumulate ($b:Transaction(transactionType == "POS", merchantType=="Vertinary Services") over window:time(1m) from entry-point Transactions;
$number: count($b),$list: collectList($b);$number > 2)
$c1: Transaction() from $list
$c2: Transaction(this != $c1, this.customerId ==$c1.customerId)

then
CEPFraud cepFraud = new CEPFraud();
cepFraud.setTransaction($c2);
cepFraud.setFraudReason("More than 2 txns for same customer");
insert(cepFraud);
end